name: website build and lint
on:
    push:
        branches: [master]
        paths:
            - "docs/**"
            - "schemas/**"
            - ".github/workflows/docs.yml"
    pull_request:
        types: [opened, synchronize]
        paths:
            - "docs/**"
            - "schemas/**"
            - ".github/workflows/docs.yml"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
    node:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./docs
        steps:
            - name: ğŸ›  Setup Node.JS
              uses: actions/setup-node@v3

            - name: ğŸ”§ Install the rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: ğŸ“¥ Checkout repo
              uses: actions/checkout@v3

            - name: ğŸ“„ Generate docs from JSON schema
              run: cargo run --bin generate_wiki

            - name: ğŸ›  Install dependencies
              run: npm ci

            - name: ğŸ–‹ï¸ Run lint + typecheck + build
              run: npm run typecheck && npm run lint --max-warnings=0 && npm run build
