name: macos lint
on:
    workflow_dispatch: {}
    push:
        branches: [master]
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
    check:
        runs-on: macos-14
        steps:
            - name: ğŸ›  Install system dependencies
              run: brew install ffmpeg

            - name: ğŸ”§ Install the rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy

            - name: ğŸ“¥ Checkout repo
              uses: actions/checkout@v4

            - name: ğŸ“ Rust cache
              uses: Swatinem/rust-cache@v2

            - name: ğŸª¢ Generate Chromium Embedded Framework bindings
              run: cargo build --package compositor_chromium

            - name: ğŸ“– Check formatting
              run: cargo fmt --all --check

            - name: ğŸ“ Run clippy
              run: cargo clippy --workspace --all-targets -- -D clippy::todo -D warnings

