name: web renderer lint
on: [push]

jobs:
    node:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web_renderer
        steps:            
            - name: ğŸ›  Use node.js
              uses: actions/setup-node@v3

            - name: ğŸ“¥ Checkout repo
              uses: actions/checkout@v3

            - name: ğŸ›  Install deps
              run: npm ci

            - name: ğŸ–‹ï¸ Run lint
              run: npm run lint
            
