name: wasm build
on:
    push:
        branches: [master]
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
    check:
        runs-on: ubuntu-24.04
        steps:
            - name: ğŸ›  Install system dependencies
              run: |
                  set -e

                  echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections

                  sudo apt-get update -y -qq
                  sudo apt-get install -y mesa-vulkan-drivers libegl1-mesa-dev libgl1-mesa-dri libxcb-xfixes0-dev ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev ttf-mscorefonts-installer libopus-dev

                  fc-cache -f

                  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

            - name: ğŸ”§ Install the rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: ğŸ“¥ Checkout repo
              uses: actions/checkout@v4

            - name: ğŸ“ Rust cache
              uses: Swatinem/rust-cache@v2

            - name: ğŸ›  wasm-pack build
              run: wasm-pack build --target web compositor_web

